version: 2
jobs:
  build:
    # working_directory: /workdir
    docker:
      - image: circleci/buildpack-deps:19.10

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.09.3

      - run:
          name: Docker info
          command: |
            if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
              sudo chown ${UID} /var/run/docker.sock
            fi
            docker version
            docker info

      - restore_cache:
          keys:
            - cache-{{ .Branch }}

      - run:
          name: Loading docker cache
          command: |
            if [[ -f /cache/layers.tar ]]; then
              docker load -i /cache/layers.tar
            fi

      - run:
          name: Build docker image
          command: |
            make build

      - run:
          name: Test
          command: |
            sudo make test-setup
            sudo apt-get install expect
            make -d test

      - run:
          name: Generate docker build image cache
          command: |
            mkdir -p /cache
            docker save -o /cache/layers.tar ${IMAGE_NAME}

      - save_cache:
          key: cache-{{ .Branch }}-{{ epoch }}
          paths:
            - /cache/layers.tar

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
