version: 2
jobs:
  build:
    # working_directory: /workdir
    docker:
      - image: circleci/buildpack-deps:19.10

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.09.3

      - run:
          name: Docker info
          command: |
            if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
              sudo chown ${UID} /var/run/docker.sock
            fi
            docker version
            docker info

      - run:
          name: Build docker image
          command: |
            make build

      - run:
          name: Test
          command: |
            if curl -o /dev/null -sf http://169.254.169.254:3142/; then
            sudo sh -c 'cat > /etc/apt/apt.conf.d/01proxy <<EOF
            Acquire::HTTP::Proxy "http://169.254.169.254:3142/";
            Acquire::HTTPS::Proxy false;
            EOF'
            fi
            sudo make test-setup
            sudo apt-get install expect
            make test


workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
